
version: "3"
services:
  node:
    build: .
    container_name: bot-api
    restart: always
    ports:
      - 8000:8000
    networks:
      - docker-service
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: docker-mariadb
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - docker-service
    volumes:
      - maria-data:/data/db

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local